package hibernate.entity;
// Generated Jun 24, 2020 11:10:55 AM by Hibernate Tools 4.3.1



/**
 * JawabanPesertaId generated by hbm2java
 */
public class JawabanPesertaId  implements java.io.Serializable {


     private String username;
     private int idSoalkuis;

    public JawabanPesertaId() {
    }

    public JawabanPesertaId(String username, int idSoalkuis) {
       this.username = username;
       this.idSoalkuis = idSoalkuis;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getIdSoalkuis() {
        return this.idSoalkuis;
    }
    
    public void setIdSoalkuis(int idSoalkuis) {
        this.idSoalkuis = idSoalkuis;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JawabanPesertaId) ) return false;
		 JawabanPesertaId castOther = ( JawabanPesertaId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && (this.getIdSoalkuis()==castOther.getIdSoalkuis());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + this.getIdSoalkuis();
         return result;
   }   


}


