package hibernate.entity;
// Generated Jun 22, 2020 5:02:31 PM by Hibernate Tools 4.3.1



/**
 * Peserta generated by hbm2java
 */
public class Peserta  implements java.io.Serializable {


     private int idPeserta;
     private String username;
     private String password;
     private String nama;
     private Integer nim;
     private String prodi;
     private String angkatan;
     private String email;

    public Peserta() {
    }

	
    public Peserta(int idPeserta) {
        this.idPeserta = idPeserta;
    }
    public Peserta(int idPeserta, String username, String password, String nama, Integer nim, String prodi, String angkatan, String email) {
       this.idPeserta = idPeserta;
       this.username = username;
       this.password = password;
       this.nama = nama;
       this.nim = nim;
       this.prodi = prodi;
       this.angkatan = angkatan;
       this.email = email;
    }
   
    public int getIdPeserta() {
        return this.idPeserta;
    }
    
    public void setIdPeserta(int idPeserta) {
        this.idPeserta = idPeserta;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getNim() {
        return this.nim;
    }
    
    public void setNim(Integer nim) {
        this.nim = nim;
    }
    public String getProdi() {
        return this.prodi;
    }
    
    public void setProdi(String prodi) {
        this.prodi = prodi;
    }
    public String getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(String angkatan) {
        this.angkatan = angkatan;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


