package hibernate.entity;
// Generated Jun 22, 2020 5:02:31 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private String status;

    public User() {
    }

	
    public User(String username) {
        this.username = username;
    }
    public User(String username, String password, String email, String status) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.status = status;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


